# -*- coding: utf-8 -*-
"""Twitter_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zim-KTSTV26dVT32u-ikGwVr5u-0QIoO
"""

pip install snscrape

import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "Marah lang:id until:2022-09-03 since:2022-08-10"
tweets = []
limit = 500


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.username, tweet.content])
        
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])
print(df)

df.to_csv('tweets.csv')